name: aesthetic-lens
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - flask=2.0.1
  - tensorflow=2.10.0
  - pillow=9.0.1
  - numpy=1.22.3
  - scipy=1.8.0
  - matplotlib=3.5.1
  - pip=22.0.4
  - pip:
    - tensorflow-hub==0.12.0
